---
- name: "Configure the EKS cluster with kubectl"
  hosts: manager[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ANSIBLE_HOST_KEY_CHECKING: False

  tasks:
    - name: Copying deployment configuration
      copy:
        src: "K8s-deployment.yml"
        dest: $HOME

    - name: Applying deployment configuration
      shell: "kubectl apply -f K8s-deployment.yml"
      args:
        chdir: $HOME

    - name: Copying load balancer configuration
      copy:
        src: "K8s-cluster-load-balancer.yml"
        dest: $HOME

    - name: Creating service configuration
      command: "kubectl apply -f K8s-cluster-load-balancer.yml"
      args:
        chdir: $HOME