- name: "Deploy app"
  hosts: manager[0]
  user: ubuntu
  gather_facts: false
  become: yes

  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"

  tasks:
    - name: Deploying image from dockerhub to K8s cluster
      shell: "kubectl set image deployments/prashant-final-project-deployment prashant-final-project-app=black07/prashant-final-project-app:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: Check if deployment ist successful
      shell: "kubectl rollout status deployments/prashant-final-project-deployment"
      args:
        chdir: $HOME

    - name: Get the LoadBalancer's DNS name
      shell: "kubectl get svc prashant-final-project-app-load-balancer"
      register: elb_dns
      args:
        chdir: $HOME

    - name: Application endpoint
      debug:
        msg: "Endpoint : {{ elb_dns.stdout }}"
