- name: "Deploy app"
  hosts: manager[0]
  user: ubuntu
  gather_facts: false
  become: yes

  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"

  tasks:
    - name: Deploying image from dockerhub to K8s cluster
      shell: "kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}-app=black07/prashant-final-project-app:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: Check if deployment ist successful
      shell: "kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME
