apiVersion: v1
kind: Service
metadata:
  name: prashant-final-project-app-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: prashant-final-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

