version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: black07/prashant-final-project-app
    docker:
      - image: circleci/node:latest

jobs:
  tesing-deliverables:
    docker:
      - image:  python:3.7.3-stretch

    steps:
      - checkout

      - run :
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.23.0/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint

      - run :
          name : lint docker file
          command : |
            ./hadolint Dockerfile

      - run :
          name : lint python app
          command : |
            . env/bin/activate
            pylint --disable=R,C,W1203 app.py


  docker-upload:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building docker container
          command: |
            docker build --tag=$IMAGE_NAME:$CIRCLE_WORKFLOW_ID .
            docker image ls

      - run:
          name: Uploading Image to Dockerhub
          command: |
            echo "Docker Image: $IMAGE_NAME"
            echo "Docker username : $DOCKERHUB_USERNAME"
            docker login -u "black07" — password-stdin
            docker push $IMAGE_NAME:$CIRCLE_WORKFLOW_ID
#            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

workflows:
  default:
    jobs:
      - tesing-deliverables
      - docker-upload
