apiVersion: apps/v1
kind: Deployment
metadata:
  name: prashant-final-project-deployment
  labels:
    app: prashant-final-project-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prashant-final-project-app

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: prashant-final-project-app
    spec:
      containers:
        - name: prashant-final-project-app
          image: black07/prashant-final-project-app
          ports:
            - containerPort: 80
